<?php
namespace MrPrompt\Portabilidade;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-06-06 at 18:59:43.
 */
class CaptchaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Captcha
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Captcha;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MrPrompt\Portabilidade\Captcha::setImagem
     * @todo   Implement testSetImagem().
     */
    public function testSetImagem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Portabilidade\Captcha::getImagem
     * @todo   Implement testGetImagem().
     */
    public function testGetImagem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Portabilidade\Captcha::setTexto
     * @todo   Implement testSetTexto().
     */
    public function testSetTexto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Portabilidade\Captcha::getTexto
     * @todo   Implement testGetTexto().
     */
    public function testGetTexto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
