<?php
namespace MrPrompt\Portabilidade;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-06-06 at 18:59:43.
 */
class ConsultaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Consulta
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Consulta;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MrPrompt\Portabilidade\Consulta::baixaCaptcha
     * @todo   Implement testBaixaCaptcha().
     */
    public function testBaixaCaptcha()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Portabilidade\Consulta::consulta
     * @todo   Implement testConsulta().
     */
    public function testConsulta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
