<?php
namespace MrPrompt\Portabilidade;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-06-06 at 18:59:43.
 */
class TelefoneTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Telefone
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Telefone;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MrPrompt\Portabilidade\Telefone::setNumero
     * @todo   Implement testSetNumero().
     */
    public function testSetNumero()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Portabilidade\Telefone::getNumero
     * @todo   Implement testGetNumero().
     */
    public function testGetNumero()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
